version: "3.8"
services:
  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "bmb123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"